# Generated by Django 3.2.5 on 2021-08-22 09:29

import contacts.models.validator_fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('fa_icon', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('type', models.CharField(choices=[('ESN', 'Entreprise de services numériques'), ('SOFT', 'Editeur de logiciels'), ('ENG', 'Ingénierie'), ('IND', 'Industrie'), ('WEB', 'Création de sites internet')], max_length=4)),
                ('description', models.TextField(blank=True, default='')),
                ('address1', models.TextField(blank=True, default='', max_length=1024)),
                ('address2', models.TextField(blank=True, default='', max_length=1024)),
                ('zipcode', contacts.models.validator_fields.ZipcodeField(blank=True, default='', max_length=5)),
                ('city', models.CharField(max_length=250)),
                ('business', models.ManyToManyField(to='contacts.Business')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone_number', contacts.models.validator_fields.PhoneNumberField(blank=True, default='', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.company')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company', 'last_name'],
            },
        ),
    ]
