# Generated by Django 3.2.5 on 2021-08-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mission',
        ),
    ]
