# Generated by Django 3.2.5 on 2021-08-03 09:09

import contacts.models.validator_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address1',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='company',
            name='address2',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='company',
            name='zipcode',
            field=contacts.models.validator_fields.ZipcodeField(blank=True, default='', max_length=5),
        ),
    ]
