# Generated by Django 3.2.5 on 2021-08-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210810_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('ESN', 'Entreprise de services numériques'), ('SOFT', 'Editeur de logiciels'), ('ENG', 'Ingénierie'), ('IND', 'Industrie'), ('WEB', 'Création de sites internet')], default='ESN', max_length=4),
            preserve_default=False,
        ),
    ]
