# Generated by Django 3.2.5 on 2021-08-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20210810_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='fa_icon',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
