# Generated by Django 3.2.5 on 2021-07-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20210725_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='adress1',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='company',
            name='address2',
            field=models.TextField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
