# Generated by Django 3.2.5 on 2021-07-26 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20210725_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=250)),
                ('last_name', models.TextField(max_length=1024)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.company')),
            ],
            options={
                'ordering': ['company', 'last_name'],
            },
        ),
    ]
