# Generated by Django 3.2.5 on 2021-07-29 10:19

import contacts.models.validator_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_mission_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmember',
            name='phone_number',
            field=contacts.models.validator_fields.PhoneNumberField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='zipcode',
            field=contacts.models.validator_fields.ZipcodeField(max_length=5),
        ),
    ]
