# Generated by Django 3.2.5 on 2021-07-29 11:53

import contacts.models.validator_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20210729_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmember',
            name='phone_number',
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', contacts.models.validator_fields.PhoneNumberField(max_length=10, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contactmember')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
