# Generated by Django 3.2.5 on 2021-07-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20210729_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'ordering': ['contact']},
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='user',
            new_name='contact',
        ),
    ]
