# Generated by Django 3.2.5 on 2021-07-29 13:22

import contacts.models.validator_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20210729_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=contacts.models.validator_fields.PhoneNumberField(blank=True, max_length=10, unique=True),
        ),
    ]
