# Generated by Django 3.2.5 on 2021-08-07 15:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Company registered'), (10, 'To apply'), (20, 'Contacted by company'), (30, 'First meet incoming'), (40, 'Technical test'), (50, 'In progress'), (60, 'Offer received'), (70, 'Aborted'), (80, 'Refused by company')], default=0)),
                ('estimated_salary', models.FloatField(null=True)),
                ('proposed_salary', models.FloatField(null=True)),
                ('environment_notation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('environment_details', models.TextField(blank=True, default='')),
                ('values_notation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('values_details', models.TextField(blank=True, default='')),
                ('evolution_notation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('evolution_details', models.TextField(blank=True, default='')),
                ('knowledge_notation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('knowledge_details', models.TextField(blank=True, default='')),
                ('management_notation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('management_details', models.TextField(blank=True, default='')),
                ('advantages_notation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('advantages_details', models.TextField(blank=True, default='')),
                ('notoriety_notation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('notoriety_details', models.TextField(blank=True, default='')),
                ('office_notation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('office_details', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['proposed_salary', 'estimated_salary', 'company'],
            },
        ),
    ]
