# Generated by Django 3.2.5 on 2021-08-22 09:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Company registered'), (10, 'Action to do'), (20, 'In progress'), (30, 'Offer received'), (40, 'Aborted'), (50, 'Refused by company')], default=0)),
                ('estimated_salary', models.FloatField(null=True)),
                ('proposed_salary', models.FloatField(null=True)),
                ('environment_notation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('environment_details', models.TextField(blank=True, default='')),
                ('values_notation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('values_details', models.TextField(blank=True, default='')),
                ('evolution_notation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('evolution_details', models.TextField(blank=True, default='')),
                ('knowledge_notation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('knowledge_details', models.TextField(blank=True, default='')),
                ('management_notation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('management_details', models.TextField(blank=True, default='')),
                ('advantages_notation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('advantages_details', models.TextField(blank=True, default='')),
                ('notoriety_notation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('notoriety_details', models.TextField(blank=True, default='')),
                ('office_notation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('office_details', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['proposed_salary', 'estimated_salary', 'company'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
                ('appliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appliances.appliance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Language'), (1, 'Framework'), (2, 'Tool'), (3, 'Library'), (4, 'OS'), (5, 'Method')], null=True)),
                ('image', models.ImageField(blank=True, upload_to='skills')),
                ('related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appliances.skill')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.appliance')),
                ('skills', models.ManyToManyField(to='appliances.Skill')),
            ],
            options={
                'ordering': ['appliance', 'title'],
            },
        ),
    ]
