# Generated by Django 3.2.5 on 2021-08-05 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0002_alter_appliance_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='appliance',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appliances.appliancestatus'),
        ),
    ]
