# Generated by Django 3.2.5 on 2021-08-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0004_alter_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='related',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appliances.skill'),
            preserve_default=False,
        ),
    ]
