# Generated by Django 3.2.5 on 2021-08-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0005_alter_appliance_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplianceStatus',
        ),
    ]
