# Generated by Django 3.2.5 on 2021-08-09 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0008_alter_skill_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appliances.skill'),
        ),
    ]
