# Generated by Django 3.2.5 on 2021-08-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0009_alter_skill_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Language'), (1, 'Framework'), (2, 'Tool'), (3, 'Library'), (4, 'OS'), (5, 'Method')], null=True),
        ),
    ]
