# Generated by Django 3.2.5 on 2021-08-16 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appliances', '0010_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='status',
            field=models.IntegerField(choices=[(0, 'Company registered'), (10, 'Action to do'), (20, 'In progress'), (30, 'Offer received'), (40, 'Aborted'), (50, 'Refused by company')], default=0),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_open', models.BooleanField(default=False)),
                ('appliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appliances.appliance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
