# Generated by Django 3.2.5 on 2021-08-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0011_auto_20210816_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
