# Generated by Django 3.2.5 on 2021-08-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0012_auto_20210817_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_open',
        ),
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
