# Generated by Django 3.2.5 on 2021-08-08 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appliances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField(auto_now=True)),
                ('type', models.CharField(choices=[('PHC', 'Phone call'), ('MEE', 'Meeting'), ('OFR', 'Offer'), ('APY', 'Apply'), ('TES', 'Test')], max_length=3)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.appliance')),
            ],
        ),
    ]
